import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.jsx</code>
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <a href="/buildtime">
              <h2>Build Time &rarr;</h2>
            </a>
            <p>
              Index and Items pages built at build time. If they weren't built
              then 404.
            </p>
          </div>

          <div className={styles.card}>
            <a href="/buildcommonwithrevalidate">
              <h2>Build Time (Build Common & Revalidate) &rarr;</h2>
            </a>
            <p>
              Index and commonly used Items pages built at build time. If they
              weren&apos;t built generate live and save. Revalidate every 60
              minutes.
            </p>
          </div>

          <div className={styles.card}>
            <a href="/clientside">
              <h2>Client Side &rarr;</h2>
            </a>
            <p>Generate Index and Item pages client side</p>
          </div>

          <div className={styles.card}>
            <a href="/serverside">
              <h2>Server Side &rarr;</h2>
            </a>
            <p>Generate Index and Item pages server side</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
