name: Accessibility
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on: [deployment_status]
jobs:
  pa11y:
    # only runs this job on successful deploy
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2
      - name: Set up node for global install
        uses: actions/setup-node@v1
      - name: Install pa11y
        run: npm install -g pa11y
      - name: Run pa11y
        run: pa11y ${{ github.event.deployment_status.target_url }}
